name: Pull Request
on:
  pull_request:
    branches: [ master, main ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Yarn install
        uses: hexancore/yarn-ci-install@0.1.0
      - name: Lint
        run: yarn lint
      - name: Test
        uses: ./.github/actions/test
      - name: Build
        run: yarn build